version: '3.3'
services:
  web:
    build: ./docker/nginx
    container_name: sunrise-nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
     - "8080:80"
     - "8443:443"
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  php-fpm:
    build: ./docker/php
    container_name: sunrise-php
    ports:
      - 9001:9000
    expose:
      - "9000"
    volumes:
      - ./html:/var/www/html
    networks:
      - app-network
  db:
    image: mariadb:10.6.7
    restart: unless-stopped
    container_name: sunrise-mysql
    environment:
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '6606:3306'
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/raw:/home/
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sunrise-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 10000M
    restart: unless-stopped
    ports:
      - 8090:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  # mysql:
  #   image: mariadb:latest
  #   container_name: mysql
  #   env_file:
  #     - ".env"
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}