version: '3.9'
services:
  web:
    build: ./docker/nginx
    container_name: docker-nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
     - "8080:80"
     - "8443:443"
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/site.conf
  php-fpm:
    build: ./docker/php
    container_name: "docker-php"
    ports:
      - 9000:9000
  # mysql:
  #   image: mariadb:latest
  #   container_name: mysql
  #   env_file:
  #     - ".env"
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}